# Generated by Django 4.1.6 on 2023-04-05 13:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('OrganizationName', models.CharField(max_length=50)),
                ('CommunityName', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=255)),
                ('Location', django.contrib.gis.db.models.fields.PointField(default='POINT(0 0)', srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
