# Generated by Django 4.1.6 on 2023-04-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('CompostersAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='composter',
            name='groups',
            field=models.ManyToManyField(related_name='composter_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='composter',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='composter',
            name='user_permissions',
            field=models.ManyToManyField(related_name='composter_user_permissions', to='auth.permission'),
        ),
    ]
