# Generated by Django 4.1.6 on 2023-04-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompostItem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compost',
            name='CompostQuantity',
        ),
    ]
