# Generated by Django 4.1.6 on 2023-04-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompostItem', '0002_remove_compost_compostquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compost',
            name='CompostImage',
            field=models.FileField(blank=True, null=True, upload_to='composts/'),
        ),
    ]
