# Generated by Django 4.1.6 on 2023-05-02 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GreenersAccount', '0006_delete_compost'),
        ('CompostItem', '0003_alter_compost_compostimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompostOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnimalManureQuantity', models.IntegerField(blank=True, null=True)),
                ('PlantFertilizersQuantity', models.IntegerField(blank=True, null=True)),
                ('BiodegradableFertilizersQuantity', models.IntegerField(blank=True, null=True)),
                ('StartDate', models.DateField(blank=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(choices=[('completed', 'Completed'), ('not_completed', 'Not completed')], default='not_completed', max_length=20)),
                ('Greener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Greener', to='GreenersAccount.greener')),
            ],
        ),
    ]
