# Generated by Django 4.1.6 on 2023-04-05 13:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CompostersAccount', '0002_composter_groups_composter_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Greener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('PhoneNumber', models.CharField(max_length=255)),
                ('Location', django.contrib.gis.db.models.fields.PointField(default='POINT(0 0)', srid=4326)),
                ('composter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composters', to='CompostersAccount.composter')),
            ],
        ),
    ]
