# Generated by Django 4.1.6 on 2023-04-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenersAccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greener',
            old_name='Password',
            new_name='password',
        ),
    ]
