# Generated by Django 4.1.6 on 2023-04-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('GreenersAccount', '0002_rename_password_greener_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='greener',
            name='groups',
            field=models.ManyToManyField(related_name='greener_groups', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='greener',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='greener',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='greener',
            name='user_permissions',
            field=models.ManyToManyField(related_name='greener_user_permissions', to='auth.group'),
        ),
    ]
