# Generated by Django 4.1.6 on 2023-04-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenersAccount', '0003_greener_groups_greener_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='greener',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
