# Generated by Django 4.1.6 on 2023-04-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenersAccount', '0005_compost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compost',
        ),
    ]
