# Generated by Django 4.1.6 on 2023-05-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenersAccount', '0008_greenernotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenernotifications',
            name='IsRead',
            field=models.BooleanField(default=False),
        ),
    ]
