# Generated by Django 4.1.6 on 2023-05-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenersAccount', '0009_greenernotifications_isread'),
    ]

    operations = [
        migrations.AddField(
            model_name='greener',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
